name: Util Library MSBuild
# Upon any change in sub files of ./util/util_msvscpp, the action does the following:
# 1. Builds the Util Library Release x64 & x86 DLL & Lib, using MSBuild
# 2. Copies the DLLs & Libs to the corresponding folders on ./lib repository folder, and commits

on: 
  push:
    paths:
    - 'util/util_msvscpp/**'
    
env:
  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE_PATH: .\util\util_msvscpp
  X86_OUTPUT_DIR: .\util\util_msvscpp\Release\ 
  X86_REPO_LIB_PTH: .\util\lib\x86\
  X64_OUTPUT_DIR: .\util\util_msvscpp\x64\Release\
  X64_REPO_LIB_PTH: .\util\lib\x64\
  X86_DLL_NAME: xhptdc8_util.dll
  X86_LIB_NAME: xhptdc8_util.lib 
  X64_DLL_NAME: xhptdc8_util_64.dll
  X64_LIB_NAME: xhptdc8_util_64.lib
  
jobs:
  build:
    runs-on: windows-latest
    defaults:
       run:
         shell: powershell
    env: 
          X86_REPO_LIB_PTH_COMMIT: ./util/lib/x86/
          X64_REPO_LIB_PTH_COMMIT: ./util/lib/x64/
          COMMIT_MSG: 'Internal build due to Util code change' 

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Build Release x86
      env:
        BUILD_PLATFORM: x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        msbuild ${{env.SOLUTION_FILE_PATH}} /m /property:Configuration=Release /property:Platform=${{env.BUILD_PLATFORM}}
        
    - name: Commit x86 DLL
      uses: EndBug/add-and-commit@v7.0.0
      with:
          author_name: Internal Workflow Action
          message: ${{env.COMMIT_MSG}}
          add: ${{env.X86_REPO_LIB_PTH_COMMIT}}${{env.X86_DLL_NAME}}

    - name: Commit x86 Lib
      uses: EndBug/add-and-commit@v7.0.0
      with:
          author_name: Internal Workflow Action
          message: ${{env.COMMIT_MSG}}
          add: ${{env.X86_REPO_LIB_PTH_COMMIT}}${{env.X86_LIB_NAME}}
